### ISSUE TITLE
[feature request] dnscrypt

### ISSUE THREAD

**Issue by alterstep** [wttw/dox#2]
dox does not support dnscrypt. Can you add it?

**Comment by wttw** [comment]
That'd be a fair bit of work, unless you know of some reasonably licensed C++ code that implements it.

([YourFriendlyDNS](https://github.com/softwareengineer1/YourFriendlyDNS) looks like a decent source of that, but under a not terribly compatible license.)

**Comment by jlivingood** [comment]
IMO since this is a DoH test tool, dnscrypt does not make sense (nor does DNSSEC, etc.). Keeping the tool very focused on a narrow purpose seems better.

**Comment by wttw** [comment]
Yeah, out of scope. At least for now.
