### ISSUE TITLE
Survey List & Targets

### ISSUE THREAD

**Issue by jlivingood** [wttw/dox#3]
Under the survey tab it'd be cool to have a way to load my own list of additional DoH servers as I did in for Query & Performance and to specify/customize the targets via the GUI.

**Comment by wttw** [comment]
You can add a list of both the DoH servers and target webservers by loading a JSON config, via File -> Load Survey...

The file format for that is entirely undocumented at the moment, but it's fairly obvious from the default file that's embedded, [defaultSurvey.json](https://github.com/wttw/dox/blob/master/defaultSurvey.json)

A GUI to edit that would be nice.

**Comment by jlivingood** [comment]
Awesome - I missed that! I suppose an alternative approach may be to load a JSON with the resolvers and it would work uniformly for query, performance, and survey. But thx for the heads up on what I missed in the UI.
