### ISSUE TITLE
Simplify Install

### ISSUE THREAD

**Issue by jlivingood** [wttw/dox#4]
Eventually figured out the install. Would be cool just to make a .dmg available via some URL for Mac users.

**Comment by kontrolldkaos** [comment]
I would like to second this suggestion.

**Comment by wttw** [comment]
There's a dmg and a windows zip file on the releases page - https://github.com/wttw/dox/releases

There are a few things that need doing to really make the install simpler...

1. Sign the code and installers on both windows and mac
2. Actually have an installer on windows (I've used [wix](https://wixtoolset.org) to do that before).
3. Persuade buildkite to publish the build artefacts to github
4. Link to them from README.md

I'm waiting on Dun & Bradstreet to update some information so I can renew my code-signing certificates, but the rest should be easy enough.

For Linux some "build from source" docs and .deb / .rpms should be enough. I'll create some issues to track that.

**Comment by jlivingood** [comment]
Ack - now see it at https://github.com/wttw/dox/releases - thanks! Issue can be closed after you get certs renewed I suppose.

**Comment by theo19** [comment]
How about externalizing the json files that contain the list of target sites and target servers, so that we can re-use the data collected elsewehre, for example importing and filtering it from https://github.com/catap/namebench/blob/master/config/servers.csv

**Comment by theo19** [comment]
For the targetrs, i think the scpoing is REALLY  important to put results into proper perspective -  importing targtes from https://github.com/catap/namebench/blob/master/data/alexa-top-2000-domains.txt makes no sense if your customer/own markets top 2000 are rather different. Queries are in part driven by local events and demands, and ideally you benchmark the set of the most local DNS services there is, against the global over the top DNS ones, using current Top 2000 focussed in YOUR OWN geography...

**Comment by wttw** [comment]
We have signed installers for windows and mac now, being built as part of the release process.
