### ISSUE TITLE
Externalizing json Data files with target sites and target servers 

### ISSUE THREAD

**Issue by theo19** [wttw/dox#6]
How about externalizing the json files that contain the list of target sites and target servers, so that we can re-use the data collected elsewehre, for example allowing importing and filtering it from https://github.com/catap/namebench/blob/master/config/servers.csv 

Filtering woud be by gwography/local policy (assuming one country will have a different loal policy then another country. Telecommunicatisn regulation specifically inclduing privacy policy seeme to be divided and managed par country according to ITU/United-Nations agreed structures.  _Originally posted by @theo19 in https://github.com/wttw/dox/issues/4#issuecomment-513470809_

**Comment by wttw** [comment]
I'm not sure exactly what you mean. The end user can load lists of resolvers and targets from a local json file, and can save the results out as machine-readable json (with the possible plan of uploading that data to an aggregator, if anyone wanted to run such a thing).

**Comment by theo19** [comment]
Thats great, i seem to have missed that which file, path do i have to use?
![grafik](https://user-images.githubusercontent.com/11328661/62224541-2c972200-b3b7-11e9-900c-f22f3b1682ed.png)

**Comment by theo19** [comment]
Sorry, i was obviously blindfolded when looking at this. Closed! 
And many, many thanks. 
Now we need to have same thing as Android and iOS App...  ;-)
